### ISSUE TITLE
Unable  to run it locally

### ISSUE THREAD

**Issue by sanknm** [mikhail-angelov/react-whiteboard#1]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.9.5
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-board@1.0.0~prestart: react-board@1.0.0
6 silly lifecycle react-board@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle react-board@1.0.0~start: react-board@1.0.0
8 verbose lifecycle react-board@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-board@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\NewProject\today\react-whiteboard\node_modules\.bin;C:\Program Files\Git\cmd;C:\Users\sankalp\AppData\Roaming\npm;C:\Program Files\Git\bin\git.exe; ;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Easysoft Limited\Easysoft JDBC-Access Gateway\Libs\;C:\Program Files\Common Files\Easysoft\Shared\;C:\Program Files\Easysoft Limited\Easysoft JDBC-Access Gateway\32-Bits\Libs\;C:\Program Files (x86)\Common Files\Easysoft\Shared\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\nodejs;C:\Program Files (x8
10 verbose lifecycle react-board@1.0.0~start: CWD: C:\NewProject\today\react-whiteboard
11 silly lifecycle react-board@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'npm run env NODE_ENV=development&node dev-server ./webpack/config' ]
12 silly lifecycle react-board@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle react-board@1.0.0~start: Failed to exec start script
14 verbose stack Error: react-board@1.0.0 start: `npm run env NODE_ENV=development&node dev-server ./webpack/config`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-board@1.0.0
16 verbose cwd C:\NewProject\today\react-whiteboard
17 error Windows_NT 6.3.9600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.9.5
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-board@1.0.0 start: `npm run env NODE_ENV=development&node dev-server ./webpack/config`
22 error Exit status 1
23 error Failed at the react-board@1.0.0 start script 'npm run env NODE_ENV=development&node dev-server ./webpack/config'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-board package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run env NODE_ENV=development&node dev-server ./webpack/config
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-board
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-board
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by mikhail-angelov** [comment]
Hi, I cannot reproduce this particular issue since I do not have Windows box
but I found some issue in webpack config and make it work

just to make sure you run this app properly, there is a sequence of commands:
> npm i webpack webpack-dev-server -g
> npm i
> npm start
